name: Build & Release Image

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release tag
        id: release-tag
        run: |
          source .env
          ./scripts/create-tag.sh

      - name: Check for existing release
        id: check-release
        uses: mukunku/release-exists-action@v1.0.0
        with:
          tag: ${{ steps.release-tag.outputs.release_tag }}

      - name: Cancel if release exists
        if: steps.check-release.outputs.exists == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}

      - name: Install Qemu
        run: sudo apt-get update && sudo apt-get install qemu-system -y

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Build image with Packer
        run: |
          packer init .
          packer build \
            -var kvm=false \
            -var image_base_url="${{ steps.release-tag.outputs.image_base_url }}" \
            -var image_name="${{ steps.release-tag.outputs.image_name }}" \
            -var release_tag="${{ steps.release-tag.outputs.release_tag }}" \
            .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release-tag.outputs.release_tag }}
          files: images/*
